# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelurbano', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersorigins',
            old_name='origin',
            new_name='origin_name',
        ),
        migrations.AddField(
            model_name='offers',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hotelurbano.Product'),
            preserve_default=False,
        ),
    ]
