# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelurbano', '0002_auto_20160425_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='prod_images/'),
        ),
    ]
